# Generated by Django 4.1.5 on 2023-01-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_engineer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
